/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package imitation.events;
import com.google.cloud.firestore.Firestore;
import com.google.firebase.cloud.FirestoreClient;
import imitation.events.Login;
import imitation.events.FirebaseConfig;


public class App {
   

    public static void main(String[] args) {
        new FirebaseConfig().initFirebase();
        
        Firestore db = FirestoreClient.getFirestore();
        
        Login loginScreen = new Login(db);
        
        loginScreen.setVisible(true);
    }
}
